[package]
name = "mods_cf"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.6"
chrono = { version = "0.4.42", features = ["serde"] }
dotenvy = { git = "https://github.com/allan2/dotenvy", features = ["macros"] }
env_logger = "0.11.8"
log = { version = "0.4.28", features = ["serde"] }
reqwest = { version = "0.12.24", default-features = false, features = ["http2", "charset", "json", "gzip", "brotli", "zstd", "deflate", "rustls-tls-native-roots"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_repr = "0.1.20"
tokio = { version = "1.48.0", features = ["full"] }
